version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: 3Jkris67zhnnhz76zhn
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: 3Jkris67zhnnhz76zhn
      KC_PROXY: edge
      KC_PROXY_HEADERS: xforwarded
      KC_HTTP_ENABLED: "true"
      KC_HTTP_RELATIVE_PATH: /auth
      KC_HOSTNAME_URL: https://geotracker.duckdns.org/auth/
      KC_HOSTNAME_ADMIN_URL: https://geotracker.duckdns.org/auth/
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      JAVA_OPTS_APPEND: "-Xms256m -Xmx512m"
    command: start
    ports:
      - "8040:8080"
    depends_on:
      - keycloak-db
    restart: unless-stopped
    networks:
      - geotracker_app-network
      - keycloak-internal
  keycloak-db:
    image: postgres:15-alpine
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: 3Jkris67zhnnhz76zhn
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - keycloak-internal
volumes:
  keycloak_data:
networks:
  geotracker_app-network:
    external: true
  keycloak-internal:
    driver: bridge